server:
  port: 8081
management:
  security:
    enabled: false
  context-path: "/manage"
security:
  require-ssl: true

spring:
  main:
    allow-circular-references: true

# SpringのSAMLセキュリティモジュールのログレベルをDEBUGに設定
logging.level.org.springframework.security.saml: DEBUG
